### ISSUE TITLE
New Bitmap freezes the app

### ISSUE THREAD

**Issue by Boivin92** [DavidYork/SpriteGenerator#1]
Hi! I just downloaded the project and tried to run it. There were a few minor hurdles but nothing too big.

But now I'm trying to run it and it looks like the following line is causing a blocking call (SpritesheetGen.cs)
_target = new Bitmap(width, height);

Any idea why?

**Comment by DavidYork** [comment]
No idea why. Sorry about the late reply, I haven't seen that.
